#' Filter the Data Matrix
#'
#' It is designed to filter out noise included in the gene expression matrix. There are two internal filter functions "pOverA" and "cv", which are from the package "genefilter"(Gentleman et al. 2018). The processed matrix (processed_data.txt) is saved in the directory "local_mode_result", which is automatically created in the location specified by "dir". \cr When using the web-browser based Shiny app, the expression matrix can also be processed with this function and then uploaded to "Step 2: upload a gene expression file".

#' @param data The path of the data matrix. In the gene expression matrix, the row and column names are usually gene IDs and sample/conditions, respectively. The sample/condition names MUST be fomatted this way: a sample name is followed by double underscore then the condition, such as “stele__140mM_48h" (Mustroph et al. 2009), where stele is the sample and 140mM_48h is the condition. One column of meta data (e.g. gene annotation) can also be included in parallel with sample/condition at the end. In the column names of sample/condition and meta data, only letters, digits, single underscore, dots are allowed. Not all samples in the matrix need to be present in the svg image, and vice versa. Only samples present in the svg image are recognised and coloured. The rows and columns can be swaped and the function identifies gene IDs by "isRowGen". \cr E.g.: system.file("extdata/example", "root_expr_ann_row_gen.txt", package = "spatialHeatmap").

#' @param sep The seprator of the data matrix, e.g. ",", "\\t", ";".

#' @param isRowGene If row names are gene IDs it is "TRUE", otherwise it is "FALSE". If the data matrix is not gene expression, this argument is set according to if the row is equivalent to gene ID, which is selected to colour the image. 

#' @param pOA It specifies parameters of the filter function "pOverA" from the package "genefilter" (Gentleman et al. 2018). It filters genes according to the proportion "p" of samples where the expression values exceeding a threshold "A". The input is a two-component vector, where the first one is the "p" and the second one is "A". The default is c(0, 0), which means no filter is applied. \cr E.g. c(0.1, 2) means genes whose expression values over 2 in at least 10\% of all samples are kept. 

#' @param CV It specifies parameters of the filter function "cv" from the package "genefilter" (Gentleman et al. 2018), which filters genes according to the coefficient of variation (CV). The input is a two-component vector, specifying the CV range. The default is c(0, 10000), where the range is set from 0 to very large (10000) so as to not apply filtering. \cr E.g. c(0.1, 5) means genes with CV between 0.1 and 5 are kept.

#' @param dir The location where the directory "local_mode_result/" is created automatically to save the processed data matrix. This argument should be the same with that from the function "adj.mod" so that the files "adj.txt" and "mod.txt" generated by "adj.mod" are saved in the same place. 

#' @return A data matrix filtered by "pOverA" and "cv" from the R package "genefilter", which is saved in the directory "local_mode_result". It is a "\\t" separated "txt" file and row names (gene IDs) will be used to display the spatial heatmaps.

#' @examples

#' data.path <- system.file("extdata/example", "root_expr_ann_row_gen.txt", package = "spatialHeatmap")
#' exp <- filter.data(data=data.path, sep="\t", isRowGene=TRUE, pOA=c(0, 0), CV=c(0.1, 10000), dir="./")

#' @author Jianhai Zhang \email{jzhan067@@ucr.edu; zhang.jianhai@@hotmail.com} \cr Dr. Thomas Girke \email{thomas.girke@@ucr.edu}

#' @references
#' Gentleman, R, V Carey, W Huber, and F Hahne. 2018. “Genefilter: Methods for Filtering Genes from High-Throughput Experiments.” http://bioconductor.uib.no/2.7/bioc/html/genefilter.html \cr Matt Dowle and Arun Srinivasan (2017). data.table: Extension of `data.frame`. R package version 1.10.4. https://CRAN.R-project.org/package=data.table 
#' Mustroph, Angelika, M Eugenia Zanetti, Charles J H Jang, Hans E Holtan, Peter P Repetti, David W Galbraith, Thomas Girke, and Julia Bailey-Serres. 2009. “Profiling Translatomes of Discrete Cell Populations Resolves Altered Cellular Priorities During Hypoxia in Arabidopsis.” Proc Natl Acad Sci U S A 106 (44): 18843–8

#' @export
#' @importFrom data.table fread
#' @importFrom genefilter filterfun pOverA cv genefilter
#' @importFrom utils write.table
#' @importFrom kableExtra kable_styling
#' @importFrom knitr kable

filter.data <- function(data, sep, isRowGene, pOA=c(0, 0), CV=c(0, 10000), dir="./") {

    # require(data.table); require(genefilter)
    path <- paste0(dir, "/local_mode_result/")
    if (!dir.exists(path)) dir.create(path)

    exp <- fread(data, sep=sep, header=TRUE, fill=TRUE); c.na <- colnames(exp)[-ncol(exp)]
    r.na <- as.data.frame(exp[, 1])[, 1];  df <- as.data.frame(exp, stringsAsFactors=FALSE)[, -1] 
    rownames(df) <- r.na; colnames(df) <- c.na
    if(isRowGene==FALSE) df <- t(df)
    idx <- grep("__", colnames(df)); idx1 <- setdiff(seq_len(ncol(df)), idx)
    gene2 <- df[, idx, drop=FALSE]; gene3 <- df[, idx1, drop=FALSE]
    gene2 <- apply(gene2, 2, as.numeric) # This step removes rownames of gene2.

    ffun <- filterfun(pOverA(pOA[1], pOA[2]), cv(CV[1], CV[2]))
    filtered <- genefilter(gene2, ffun)
    gene2 <- gene2[filtered, ]; gene3 <- gene3[filtered, , drop=FALSE]
    # gene2 have no rownames, after "cbind.data.frame" it has same names with gene3.
    df1 <- cbind.data.frame(gene2, gene3, stringsAsFactors=FALSE) 
    write.table(df1, paste0(path, "processed_data.txt"), sep="\t", row.names=TRUE, col.names=TRUE); return(df1)

}







