#' Extracting combinations of optimal settings across data sets
#'
#' After coclustering optimization, visualize AUCs generated by optimal parameter settings on validating data sets.

#' @param auc.lis A list of AUCs from each single cell dataset that is returned by \code{auc_by_dataset}. 
#' @param auc.min An AUC value cutoff. Only AUCs above this cutoff are considered.  
#' @return An object of ggplot.

#' @examples

#' # Create parameter settings and corresponding aucs.
#' df.auc <- data.frame(auc=runif(n=5, min=1e-12, max=.99))
#' ran <- seq(0.2, 0.8, 0.1)
#' df.spd <- data.frame(sim=sample(ran, 5, replace=FALSE), sim.p=sample(ran, 5, replace=FALSE), dim=sample(seq(5, 40, 1), 5, replace=FALSE))
#' df.spd$spd.set <- paste0('s', df.spd$sim, 'p', df.spd$sim.p, 'd', df.spd$dim)
#' 
#' df.auc <- cbind(df.spd, df.auc)
#' # Plot the aucs.
#' auc_bar(df.auc, auc='auc', thr=0.5) 

#' # See package vignette by calling "browseVignettes('spatialHeatmap')".

#' @author Jianhai Zhang \email{jzhan067@@ucr.edu} \cr Dr. Thomas Girke \email{thomas.girke@@ucr.edu}

#' @export final_setting

final_setting <- function(auc.lis, auc.min=0) {
  index <- NULL; for (i in auc.lis) {
    i <- subset(i, auc > auc.min); index <- c(index, i$index)
  }
  tab <- table(index)
  # Optimal settings overlapping across validation results.
  opt <- names(tab[tab==length(auc.lis)])
  # Rank optimal settings by mean AUCs.
  auc.all <- do.call(rbind, auc.lis)[, c('auc', 'index')]
  auc.all.ag <- aggregate(auc.all$auc, list(auc.all$index), FUN=mean)
  colnames(auc.all.ag) <- c('index', 'auc.mean')
  auc.all.ag <- auc.all.ag[order(-auc.all.ag$auc.mean), ]
  for (i in seq_along(auc.lis)) {
     auc.lis[[i]] <- auc.lis[[i]][auc.all.ag$index, ]
  }
  shared <- subset(auc.lis[[1]], index %in% opt)[, c('index', 'norm', 'filter', 'dimred', 'graph.meth', 'sim', 'sim.p', 'dim', 'spd.set')]; shared
}
